### ISSUE TITLE
Certificate problem

### ISSUE THREAD

**Issue by gomesj1** [opravdin/weback-hass#6]
After adding to the configuration.yaml I can see in the home-assistant.log an

SSL validation failed for https://data.iot.eu-central-1,amazonaws.com/things/... [SSL: CERTIFICATE_VERIFY_FAILED]...

**Comment by kornelremete** [comment]
Same here

**Comment by opravdin** [comment]
Related with https://github.com/opravdin/weback-unofficial/issues/9
Will be fixed soon

**Comment by fmontebaur** [comment]
same here after Update to 2020.12.7

**Comment by a8ree** [comment]
Looking forward to this being fixed.....any ETA?

**Comment by w3corp** [comment]
Just to report. Same issue here. Thanks

**Comment by timdreier** [comment]
Same for me.

**Comment by xator91** [comment]
Same error.

**Comment by dgtlptry** [comment]
Please fix

**Comment by vityz** [comment]
I'm fixed it problem at my HASS. You need replace “cacert.pem” located in “/srv/homeassistant/lib/python3.7/site-packages/certifi/“ from older version from 2020.11.08, link:
https://github.com/certifi/python-certifi/blob/015cba9d2492a4cddaf5efe40666c18a2b259c93/certifi/cacert.pem

**Comment by timdreier** [comment]
@vityz this is probably just a temporary fix, since it will be overridden by an update of certify. Certify dropped the certificates Amazon uses on this server.

I think I found a real fix by determination the real endpoint name, I already create a pull request in the [related package](https://github.com/opravdin/weback-unofficial/issues/9) which will hopefully fix this issue permanently. Hopefully @opravdin will find some time to look into that!

**Comment by timdreier** [comment]
Since my PR is not merged yet, I created a fork, which requires the fixed version of opravdins package. You can just swap the repo in HACS until the fix is merged here: [https://github.com/timdreier/weback-hass](https://github.com/timdreier/weback-hass). There shouldn't be any change needed in your config.yaml.

**Comment by a8ree** [comment]
Many thanks for doing that. I'm up and running now

Cheers

**Comment by dgtlptry** [comment]
> Since my PR is not merged yet, I created a fork, which requires the fixed version of opravdins package. You can just swap the repo in HACS until the fix is merged here: https://github.com/timdreier/weback-hass. There shouldn't be any change needed in your config.yaml.

Hey, I´m quite new to HA and dont really understand the fix. What or which file is the "repo" and how to change it againt which other file? Could you please help by giving a short but more detailed step by step instruction? Thanks a lot

**Comment by prageeth** [comment]
This issue is now fixed in the latest version. I've tested it and it's working.
Fixed as of https://github.com/opravdin/weback-hass/releases/tag/v1.0.3

**Comment by opravdin** [comment]
Fixed in latest version of package. Update through HACS or manually.
